### ISSUE TITLE
Some questions about model implementation

### ISSUE THREAD

**Issue by TLB-MISS** [brown-ivl/ConDor#4]
First of all, thank you so much for revealing such a wonderful work!
I have some questions about your implementation of the paper.
(The version I'm currently referencing is ConDor_pytorch)

1. There are four types of pcd output from the model: `x_input`, `points_inv`, `y_p`, `x_canonical`. According to the paper's notation, I think `x_input` is $X$, `points_inv` is $X^c$, `y_p` is $EX^c$, and `x_canonical` is $E^TX$. If so, is the final output you are considering here `points_inv` or `x_canonical`? Of course, when the training goes well, the two are almost the same, but I wonder if the final output is formally considered as $X^c$ or $E^TX$(I remember that there was no mention of $E^TX$ in the paper).
2. You added `chamfer_distance` loss to your code implementation which is not in the paper. Is it really necessary? Since it is a loss within the same instance anyway, I think it is no different from the L2 loss. In my opinion, in order for the chamfer loss to be meaningful (to play a role distinct from L2), I think that the chamfer distance with other instances in the category should be calculated like the CC metric. If my guess (the L2 loss and the chamfer loss are essentially the same in the same instance) is wrong, I'd really appreciate it if you could tell me the reason!

Thanks

**Comment by RahulSajnani** [comment]
Hi Sangwon,

Thank you for showing interest in out work!

1. We use the x_canonical as the final output as our primary goal of canonicalization is to estimate E. You are correct that  x_input is ```X```, points_inv is ``` X^c``` , y_p is ```EX^c``` , and x_canonical is  ```E^t X```. We can then canonicalize ```X``` to ```X^c``` using ```E^T X``` and so we use x_canonical as the final output of our network.
2. The model will work without chamfer distance too. I was trying to optimize the arch to work better with symmetric objects that was done long after the paper was accepted which is why the loss is not in the paper.

**Comment by TLB-MISS** [comment]
@RahulSajnani 

Thank you for your kind reply!!

**Comment by RahulSajnani** [comment]
@TLB-MISS 
I am closing this issue now, feel free to reopen it if you have more queries.

**Comment by TLB-MISS** [comment]
@RahulSajnani 

I have a additional question regarding code for segmentation task.
In [this](https://github.com/brown-ivl/ConDor/blob/main/ConDor/trainers/trainer_main.py#L30) code, `equilibrium_loss` and `spatial_loss` are applied together. However, the two perform opposite roles(`equilibrium_loss` plays a role in distributing probabilities evenly to all classes, and `spatial_loss` plays a role in gathering probabilities into a specific class).
Is there any reason to use the two together?

Thanks.

**Comment by RahulSajnani** [comment]
Hi @TLB-MISS 
Equilibrium loss is applied to distribute capsules across the entire shape. Spatial loss tries to ensure that a point belongs to one capsule only.
