### ISSUE TITLE
Producing Partial Shapes

### ISSUE THREAD

**Issue by xclucas** [brown-ivl/ConDor#6]
Thanks for this great work!

In the experiments section, you mention

> For partial shapes, we either randomly slice shapes from the above datasets, or we use the more challenging ShapeNet-COCO dataset

Is this code for slicing shapes available? 

Thanks!

**Comment by RahulSajnani** [comment]
Hi @Reschivon,
Please check out: https://github.com/brown-ivl/ConDor/blob/d9e03194134c46fc19935777360ad1259b7f4ab7/ConDor/trainers/trainer_exp.py#L52-L58 for slicing shapes during training.

**Comment by xclucas** [comment]
@RahulSajnani I didn't notice this earlier, thank you!
